task:
  auto_cancellation: true

  env:
    matrix:
      PY_VER: "3.6"
      PY_VER: "3.7"

  matrix:
    - name: linux
      container:
        image: gcc:latest
        memory: 6G
      env:
        PATH: $HOME/conda/bin:$PATH
      system_script:
        - apt-get update
        - apt-get install -y libgl1-mesa-glx
      conda_script:
        - curl https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh > install.sh
        - bash ./install.sh -b -p $HOME/conda
        - conda update -yn base conda
        - conda install -y python=$PY_VER

  install_script:
    - python -m pip install --retries 3 --upgrade pip
    - pip install --retries 3 -r requirements.txt
    - python setup.py develop

  check_script:
    - pip list
    - python -c "import napari_gui; print(napari_gui.__version__)"

  test_script:
    - pytest -v
    
